services:
  brainbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./src/dal/database:/app/src/dal/database:rw
    environment:
      - NODE_ENV=production

